services:
  # PostgreSQL Database
  tv-postgres:
    image: postgres:16
    container_name: tv-postgres
    ports:
      - "5433:5432"
    env_file:
      - env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tv-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tv_admin -d theravillage"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main API Service
  tv-api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.dev
    container_name: tv-api
    ports:
      - "8083:8080"
    env_file:
      - env.local
    volumes:
      - ./services/api:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      tv-postgres:
        condition: service_healthy
      tv-ai:
        condition: service_started
    networks:
      - tv-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  # AI Service for AI Recommendations
  tv-ai:
    build:
      context: ./services/ai
      dockerfile: Dockerfile
    container_name: tv-ai
    ports:
      - "8001:8000"
    env_file:
      - env.local
    volumes:
      - ./services/ai:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    networks:
      - tv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tv-network:
    driver: bridge

volumes:
  postgres_data:
